<?php
if( function_exists('acf_add_local_field_group') ):

  acf_add_local_field_group(array(
    'key' => 'group_5df67a4f1fef8',
    'title' => 'Advanced Separator',
    'fields' => array(
      array(
        'key' => 'field_5df67a8e00388',
        'label' => 'Width',
        'name' => 'width',
        'type' => 'number',
        'instructions' => 'width with %, ex: 50%',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '33.333',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'min' => 0,
        'max' => 100,
        'step' => '',
      ),
      array(
        'key' => 'field_5df67cfb0038a',
        'label' => 'Style',
        'name' => 'style',
        'type' => 'select',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '33.3333',
          'class' => '',
          'id' => '',
        ),
        'choices' => array(
          'dashed' => 'Dashed',
          'dotted' => 'Dotted',
          'solid' => 'Solid',
        ),
        'default_value' => array(
        ),
        'allow_null' => 0,
        'multiple' => 0,
        'ui' => 0,
        'return_format' => 'value',
        'ajax' => 0,
        'placeholder' => '',
      ),
      array(
        'key' => 'field_5df75d758e506',
        'label' => 'weight',
        'name' => 'weight',
        'type' => 'number',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '33.333',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'min' => 0,
        'max' => '',
        'step' => '',
      ),
      array(
        'key' => 'field_5df6802601f7c',
        'label' => 'Position',
        'name' => 'position',
        'type' => 'select',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'choices' => array(
          'left' => 'Left',
          'right' => 'Right',
          'center' => 'Center',
        ),
        'default_value' => array(
        ),
        'allow_null' => 0,
        'multiple' => 0,
        'ui' => 0,
        'return_format' => 'value',
        'ajax' => 0,
        'placeholder' => '',
      ),
      array(
        'key' => 'field_5df67ce200389',
        'label' => 'Color',
        'name' => 'color',
        'type' => 'color_picker',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '#ffffff',
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'block',
          'operator' => '==',
          'value' => 'acf/advanced-separator',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
  ));
  
endif;
?>